### ISSUE TITLE
what your num of parameter?

### ISSUE THREAD

**Issue by JunyaoHu** [ningshuliang/MIMO-VP#1]

**Comment by JunyaoHu** [comment]
Update, I think it is `main.py`

**Comment by JunyaoHu** [comment]
I want to know how many parameters are there?
I run the code it says 30,220,800

![image](https://user-images.githubusercontent.com/67564714/232260215-9c236390-5659-402c-9b0e-7197925a42b5.png)

but in your paper you say 20,200,000

![image](https://user-images.githubusercontent.com/67564714/232260240-3497ebd0-d198-4ce5-bcab-89291ee9f849.png)

**Comment by ningshuliang** [comment]
Yes, I just check it again, this is a typo error, the real number of parameters is 30.2 M. Sorry for this error.

**Comment by JunyaoHu** [comment]
thanks！
